name: security-actions

on:
  workflow_dispatch:
    
jobs:
  checkout-and-package:
    runs-on: windows-2022

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
    
      - name: Build the App
        working-directory: ./app/
        run: | 
          dotnet publish -c Debug -p:UseAppHost=false
          dir app/bin/Debug/net8.0/

      - name: Zip Application Files 
        uses: vimtor/action-zip@v1
        with:
          files: app/bin/Debug/net8.0/
          dest: verademodotnetcore.zip

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-target
          path: app/bin/Debug/*.zip