name: security-actions

on:
  workflow_dispatch:
    
jobs:
  checkout-and-build:
    runs-on: windows-2022

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
    
      - name: Build the App
        working-directory: ./app/
        run: | 
          dotnet publish -c Debug -p:UseAppHost=false
          dir bin/Debug/net8.0/publish

      - name: Zip Application Files 
        uses: vimtor/action-zip@v1
        with:
          files: app/bin/Debug/net8.0/publish
          dest: upload.zip

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-target
          path: upload.zip

  veracode-sca-scan:
    name: veracode sca scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
      
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA_TOKEN }}
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan app --update-advisor --uri-as-name

  veracode-sast-sandbox-scan:
    name: veracode sandbox scan
    runs-on: ubuntu-latest
    needs: [ checkout-and-build, veracode-sca-scan ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: scan-target
        
      - name: upload and scan 
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: 'm3academy-dotnetcore-web'
          createprofile: true
          teams: 'M3Academy'
          filepath: 'upload.zip'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 0
          criticality: 'High'
          createsandbox: true
          sandboxname: '${{ github.ref }}'

  veracode-sast-policy-pipeline-scan:
    name: veracode policy and pipeline scan
    runs-on: ubuntu-latest
    needs: [ checkout-and-build, veracode-sca-scan, veracode-sast-sandbox-scan ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: scan-target
          
      - name: upload and scan 
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: 'm3academy-dotnetcore-web'
          createprofile: true
          teams: 'M3Academy'
          filepath: 'upload.zip'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 0
          criticality: 'High'

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: "upload.zip"
          fail_build: "true"
          issue_details: true